name: toko_roti
description: Aplikasi Toko Roti Online
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.0  # Untuk lokasi GPS
  path_provider: ^2.1.0  # Untuk menyimpan data lokal
  sqflite: ^2.3.0  # Untuk database lokal sederhana

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  appwrite: ^12.0.2
  cached_network_image: ^3.2.3
  intl: ^0.17.0
flutter:
  uses-material-design: true
dependency_overrides:
  flutter_web_auth_2: ^4.0.0